/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.BikeSharing.View;

import com.BikeSharing.Model.Admin;
import com.BikeSharing.Model.Bicycle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anisa Gurabardhi
 */
public class AdminManageBicycles extends javax.swing.JFrame {
 Admin admin= new Admin();
 Bicycle bicycle = new Bicycle();
    /**
     * Creates new form AdminManageBicycles
     */
    public AdminManageBicycles() {
        initComponents();
         setResizable(false);
        setLocationRelativeTo(null);
        bicycle.fillBicycleTableAtAdmin(table, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        showUser = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NumberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        locationField = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        AvailableField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        RemoveButton1 = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("DIN", 0, 12)); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 60, -1));

        jPanel1.setBackground(new java.awt.Color(233, 227, 227));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BikeSharing/Images/bicycle111.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 440, 320));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BikeSharing/Images/if_Left_arrow_2202280 (1).png"))); // NOI18N
        jButton1.setText("Go to Manage Users Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel1.setFont(new java.awt.Font("DIN", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to Manage Bicycles Page: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, 30));

        showUser.setFont(new java.awt.Font("DIN", 0, 18)); // NOI18N
        showUser.setText("Admin");
        jPanel1.add(showUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 60, 30));

        jLabel9.setFont(new java.awt.Font("DIN", 0, 14)); // NOI18N
        jLabel9.setText("Enter value to search:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 210, 20));

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 250, -1));

        table.setFont(new java.awt.Font("DIN", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Number plate", "Location", "Status", "Who is using it"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 450, 110));

        jLabel8.setFont(new java.awt.Font("DIN", 0, 14)); // NOI18N
        jLabel8.setText("ID:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        IdField.setEditable(false);
        IdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFieldActionPerformed(evt);
            }
        });
        jPanel1.add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, 240, -1));

        jLabel2.setFont(new java.awt.Font("DIN", 0, 14)); // NOI18N
        jLabel2.setText("Number plate:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        NumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 240, -1));

        jLabel3.setFont(new java.awt.Font("DIN", 0, 14)); // NOI18N
        jLabel3.setText("Location:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        locationField.setColumns(20);
        locationField.setRows(5);
        jScrollPane2.setViewportView(locationField);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 240, -1));

        jLabel13.setFont(new java.awt.Font("DIN", 0, 14)); // NOI18N
        jLabel13.setText("Available:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 60, -1));
        jPanel1.add(AvailableField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 240, -1));

        jLabel11.setFont(new java.awt.Font("DIN", 0, 14)); // NOI18N
        jLabel11.setText("Who is using it:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 90, -1));
        jPanel1.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 240, -1));

        RemoveButton1.setFont(new java.awt.Font("DIN", 0, 12)); // NOI18N
        RemoveButton1.setText("Remove");
        RemoveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(RemoveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, -1, -1));

        UpdateButton.setFont(new java.awt.Font("DIN", 0, 12)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 550, -1, -1));

        AddButton.setFont(new java.awt.Font("DIN", 0, 12)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 60, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BikeSharing/Images/if_refresh_59198.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFieldActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

    }//GEN-LAST:event_SearchActionPerformed

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed

    }//GEN-LAST:event_SearchKeyPressed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        table.setModel(new DefaultTableModel(null, new Object[]{"ID","Number plate","Location","Available","Who is using it"}));
       bicycle.fillBicycleTableAtAdmin(table, Search.getText());
    }//GEN-LAST:event_SearchKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       int rowIndex = table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table.getModel();

        IdField.setText(model.getValueAt(rowIndex, 0).toString());
        NumberField.setText(model.getValueAt(rowIndex, 1).toString());
        locationField.setText(model.getValueAt(rowIndex, 2).toString());
        AvailableField.setText(model.getValueAt(rowIndex, 3).toString());
        UserField.setText(model.getValueAt(rowIndex, 4).toString()
        );
       

    }//GEN-LAST:event_tableMouseClicked

    private void NumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  AdminManageUsers users = new AdminManageUsers();
        users.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
     
        String numberPlate = NumberField.getText();
        String location = locationField.getText();
        String available = AvailableField.getText();
        String id_user=UserField.getText();

        

        
            bicycle.addBicycle(null, numberPlate, location, available, id_user);
            NumberField.setText("");
            locationField.setText("");
            AvailableField.setText("");
            UserField.setText("");
            
         
           
            table.setModel(new DefaultTableModel(null, new Object[]{"ID", "Number plate", "Location", "Available","Who is using it"}));
            bicycle.fillBicycleTableAtAdmin(table, "");

     
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RemoveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButton1ActionPerformed
       int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this bicycle?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            if (IdField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "No bicycle selected!");
            } else {
                int id = Integer.valueOf(IdField.getText());
                admin.deleteABicycle(id, null, null, null, null);
                table.setModel(new DefaultTableModel(null, new Object[]{"ID", "Number Plate", "Location", "Available", "Who is using it"}));
                bicycle.fillBicycleTableAtAdmin(table, "");
            }
        }
    }//GEN-LAST:event_RemoveButton1ActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
       String numberPlate = NumberField.getText();
       String location = locationField.getText();
        String available = AvailableField.getText();
        String id_user = UserField.getText();
Integer id = Integer.parseInt(IdField.getText());
admin.updateBicycle(id, numberPlate, location, available, id_user);
          table.setModel(new DefaultTableModel(null, new Object[]{"ID", "Number Plate", "Location", "Available", "Who is using it"}));
           bicycle.fillBicycleTableAtAdmin(table, "");
           new AdminManageBicycles().setVisible(true);
           this.dispose();

        
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NumberField.setText("");
        locationField.setText("");
        AvailableField.setText("");
        UserField.setText("");

       

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageBicycles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageBicycles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageBicycles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageBicycles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManageBicycles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AvailableField;
    private javax.swing.JTextField IdField;
    private javax.swing.JTextField NumberField;
    private javax.swing.JButton RemoveButton1;
    private javax.swing.JTextField Search;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UserField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea locationField;
    public javax.swing.JLabel showUser;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
