/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.BikeSharing.View;

import com.BikeSharing.Model.User;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Anisa Gurabardhi
 */
public class SignUpView extends javax.swing.JFrame {

    private final User user = new User();

    /**
     * Creates new form RegisterView
     */
    public SignUpView() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        IdNumberField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CreateAccountButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 40, 42));
        setPreferredSize(new java.awt.Dimension(1050, 600));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 42, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 280, -1));

        jLabel6.setFont(new java.awt.Font("DIN", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("DIN", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID number:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        LastNameField.setForeground(new java.awt.Color(153, 153, 153));
        LastNameField.setText("Enter last name here");
        LastNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LastNameFieldMousePressed(evt);
            }
        });
        LastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameFieldActionPerformed(evt);
            }
        });
        LastNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LastNameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(LastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, -1));

        EmailField.setForeground(new java.awt.Color(153, 153, 153));
        EmailField.setText("Enter email here");
        EmailField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmailFieldMousePressed(evt);
            }
        });
        EmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailFieldKeyReleased(evt);
            }
        });
        jPanel1.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 280, 20));

        UsernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsernameFieldMousePressed(evt);
            }
        });
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        UsernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsernameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UsernameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 280, -1));

        IdNumberField.setForeground(new java.awt.Color(102, 102, 102));
        IdNumberField.setText("Enter ID card number here");
        IdNumberField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdNumberFieldMousePressed(evt);
            }
        });
        IdNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdNumberFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdNumberFieldKeyReleased(evt);
            }
        });
        jPanel1.add(IdNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 280, -1));

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BikeSharing/Images/if_undo_back_1891408 (1).png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 60, 30));

        jLabel2.setFont(new java.awt.Font("DIN", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("DIN", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        CreateAccountButton.setBackground(new java.awt.Color(255, 255, 255));
        CreateAccountButton.setFont(new java.awt.Font("DIN", 0, 12)); // NOI18N
        CreateAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BikeSharing/Images/if_success_1646004.png"))); // NOI18N
        CreateAccountButton.setText("Create Account");
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, 30));

        jLabel5.setFont(new java.awt.Font("DIN", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BikeSharing/Images/11111111111111.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -20, 890, -1));

        jLabel10.setFont(new java.awt.Font("DIN Medium", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GET STARTED");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 200, 30));
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 280, -1));

        jLabel9.setFont(new java.awt.Font("DIN", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        NameField.setForeground(new java.awt.Color(153, 153, 153));
        NameField.setText("Enter name here");
        NameField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        NameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NameFieldMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NameFieldMousePressed(evt);
            }
        });
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        NameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/BikeSharing/Images/if_refresh_59198.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1070, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed

        String name = NameField.getText();
        String last_name = LastNameField.getText();
        String email = EmailField.getText();
        String username = UsernameField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        String password2 = String.valueOf(ConfirmPasswordField.getPassword());
        String id_card_number = IdNumberField.getText();
        

        if (user.checkUsername(username)) {
            JOptionPane.showMessageDialog(null, "Username Already exists. Try another one");
          UsernameField.setText("");
            
        } else {
           
                user.addUser(null, name, last_name, email, username, password, id_card_number);
            new MainView().setVisible(true);
            this.dispose();
            
        }

    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.hide();
        new MainView().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void LastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameFieldActionPerformed

    }//GEN-LAST:event_LastNameFieldActionPerformed

    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost

    }//GEN-LAST:event_NameFieldFocusLost

    private void NameFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameFieldMouseExited

        
        
    }//GEN-LAST:event_NameFieldMouseExited

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void NameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameFieldKeyPressed
        if (NameField.getForeground() != Color.BLACK) {
            if (NameField.getText().equals("Enter name here")) {
                NameField.setText("");
            }

        }
        NameField.setForeground(Color.BLACK);
    }//GEN-LAST:event_NameFieldKeyPressed

    private void NameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameFieldKeyReleased
        if (NameField.getText().isEmpty() == true) {
            NameField.setText("Enter name here");
            NameField.setCaretPosition(0);
            NameField.setForeground(new java.awt.Color(204, 204, 204));
        }

    }//GEN-LAST:event_NameFieldKeyReleased

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        
      NameField.setCaretPosition(0); 
      LastNameField.setCaretPosition(0); 
      EmailField.setCaretPosition(0);
      //UsernameField.setCaretPosition(0);
      IdNumberField.setCaretPosition(0);
      
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void NameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameFieldMousePressed
               NameField.setCaretPosition(0);
    }//GEN-LAST:event_NameFieldMousePressed

    private void LastNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameFieldKeyPressed

        if (LastNameField.getForeground() != Color.BLACK) {
            if (LastNameField.getText().equals("Enter last name here")) {
                LastNameField.setText("");
            }

        }
        LastNameField.setForeground(Color.BLACK);

    }//GEN-LAST:event_LastNameFieldKeyPressed

    private void LastNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameFieldKeyReleased
       if (LastNameField.getText().isEmpty() == true) {
            LastNameField.setText("Enter last name here");
            LastNameField.setCaretPosition(0);
            LastNameField.setForeground(new java.awt.Color(204, 204, 204));
        }
        
        
        
    }//GEN-LAST:event_LastNameFieldKeyReleased

    private void LastNameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastNameFieldMousePressed

  LastNameField.setCaretPosition(0);
        
       
        
        
    }//GEN-LAST:event_LastNameFieldMousePressed

    private void EmailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailFieldKeyPressed
         if (EmailField.getForeground() != Color.BLACK) {
            if (EmailField.getText().equals("Enter email here")) {
               EmailField.setText("");
            }
        }
       EmailField.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_EmailFieldKeyPressed

    private void EmailFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailFieldKeyReleased
        if (EmailField.getText().isEmpty() == true) {
            EmailField.setText("Enter email here");
            EmailField.setCaretPosition(0);
           EmailField.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_EmailFieldKeyReleased

    private void EmailFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailFieldMousePressed
        EmailField.setCaretPosition(0);
    }//GEN-LAST:event_EmailFieldMousePressed

    private void UsernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameFieldKeyPressed
//         if (UsernameField.getForeground() != Color.BLACK) {
//            if (UsernameField.getText().equals("Enter username here")) {
//                UsernameField.setText("");
//            }
//        }
//        UsernameField.setForeground(Color.BLACK);
    }//GEN-LAST:event_UsernameFieldKeyPressed

    private void UsernameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameFieldKeyReleased
//         if (UsernameField.getText().isEmpty() == true) {
//            UsernameField.setText("Enter username here");
//            UsernameField.setCaretPosition(0);
//           UsernameField.setForeground(new java.awt.Color(204, 204, 204));
//        }
    }//GEN-LAST:event_UsernameFieldKeyReleased

    private void UsernameFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameFieldMousePressed
//        UsernameField.setCaretPosition(0);
    }//GEN-LAST:event_UsernameFieldMousePressed

    private void IdNumberFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdNumberFieldKeyPressed
        if (IdNumberField.getForeground() != Color.BLACK) {
            if (IdNumberField.getText().equals("Enter ID card number here")) {
                IdNumberField.setText("");
            }
        }
        IdNumberField.setForeground(Color.BLACK);
    }//GEN-LAST:event_IdNumberFieldKeyPressed

    private void IdNumberFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdNumberFieldKeyReleased
        if (IdNumberField.getText().isEmpty() == true) {
            IdNumberField.setText("Enter ID card number here");
           IdNumberField.setCaretPosition(0);
           IdNumberField.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_IdNumberFieldKeyReleased

    private void IdNumberFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdNumberFieldMousePressed
         IdNumberField.setCaretPosition(0);
    }//GEN-LAST:event_IdNumberFieldMousePressed

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
NameField.setText("");
 LastNameField.setText("");
EmailField.setText("");
UsernameField.setText("");

 PasswordField.setText("");
      ConfirmPasswordField.setText("");
  IdNumberField.setText("");
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BackButton;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField IdNumberField;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JTextField NameField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
